// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: s3

#ifndef _S3_UI_H
#define _S3_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void slide_Animation(lv_obj_t * TargetObject, int delay);
//SCREEN:ui_spinner
void ui_spinner_screen_init(void);
extern lv_obj_t * ui_spinner;
extern lv_obj_t * spinner;
extern lv_obj_t * ui____initial_actions0;
// SCREEN: ui_home
void ui_home_screen_init(void);
extern lv_obj_t * ui_home;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label22;
// SCREEN: ui_timeall
void ui_timeall_screen_init(void);
extern lv_obj_t * ui_timeall;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
// SCREEN: ui_weather
void ui_weather_screen_init(void);
extern lv_obj_t * ui_weather;
extern lv_obj_t * ui_weatherall;
extern lv_obj_t * ui_today;
extern lv_obj_t * ui_tom;
extern lv_obj_t * ui_todaysta;
extern lv_obj_t * ui_tomsta;
extern lv_obj_t * ui_todaytem;
extern lv_obj_t * ui_tomtep;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_tepnow;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_wetdata;
// SCREEN: ui_health
void ui_health_screen_init(void);
extern lv_obj_t * ui_health;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_heartdata;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_blooddata;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_stepdata;
extern lv_obj_t * ui____initial_actions0;





LV_FONT_DECLARE(ui_font_Alibaba16);
LV_FONT_DECLARE(ui_font_Alibaba32);
LV_FONT_DECLARE(ui_font_blood);
LV_FONT_DECLARE(ui_font_cloudy16);
LV_FONT_DECLARE(ui_font_font16s4bpp);
LV_FONT_DECLARE(ui_font_font32);
LV_FONT_DECLARE(ui_font_heart);
LV_FONT_DECLARE(ui_font_icfont16);
LV_FONT_DECLARE(ui_font_rain16);
LV_FONT_DECLARE(ui_font_step);
LV_FONT_DECLARE(ui_font_tem32);
LV_FONT_DECLARE(ui_font_wet32);
LV_FONT_DECLARE(ui_font_alibaba42);
LV_FONT_DECLARE(ui_font_alibaba20);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
