// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: s3

#include "ui.h"

void ui_health_screen_init(void)
{
    ui_health = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_health, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label13 = lv_label_create(ui_health);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 1);
    lv_obj_set_y(ui_Label13, -47);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "健康");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0x48B679), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &ui_font_Alibaba16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_health);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -54);
    lv_obj_set_y(ui_Label7, -17);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xE21515), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &ui_font_heart, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_health);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -24);
    lv_obj_set_y(ui_Label8, -18);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "心率:");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &ui_font_font16s4bpp, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_health);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -51);
    lv_obj_set_y(ui_Label9, 8);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xEA0303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &ui_font_blood, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_heartdata = lv_label_create(ui_health);
    lv_obj_set_width(ui_heartdata, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_heartdata, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_heartdata, 24);
    lv_obj_set_y(ui_heartdata, -17);
    lv_obj_set_align(ui_heartdata, LV_ALIGN_CENTER);
    lv_label_set_text(ui_heartdata, "74/min");
    lv_obj_set_style_text_color(ui_heartdata, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_heartdata, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_health);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -23);
    lv_obj_set_y(ui_Label11, 9);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "血氧:");
    lv_obj_set_style_text_font(ui_Label11, &ui_font_font16s4bpp, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_blooddata = lv_label_create(ui_health);
    lv_obj_set_width(ui_blooddata, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_blooddata, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_blooddata, 15);
    lv_obj_set_y(ui_blooddata, 9);
    lv_obj_set_align(ui_blooddata, LV_ALIGN_CENTER);
    lv_label_set_text(ui_blooddata, "95%");
    lv_obj_set_style_text_color(ui_blooddata, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_blooddata, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_blooddata, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_health);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -52);
    lv_obj_set_y(ui_Label12, 36);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0x005FFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &ui_font_step, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_health);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -24);
    lv_obj_set_y(ui_Label14, 34);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "步数:");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &ui_font_font16s4bpp, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_stepdata = lv_label_create(ui_health);
    lv_obj_set_width(ui_stepdata, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_stepdata, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_stepdata, 18);
    lv_obj_set_y(ui_stepdata, 34);
    lv_obj_set_align(ui_stepdata, LV_ALIGN_CENTER);
    lv_label_set_text(ui_stepdata, "6500");
    lv_obj_set_style_text_color(ui_stepdata, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_stepdata, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}
