// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: s3

#include "ui.h"

void ui_weather_screen_init(void)
{
    ui_weather = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_weather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_weatherall = lv_label_create(ui_weather);
    lv_obj_set_width(ui_weatherall, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weatherall, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weatherall, 0);
    lv_obj_set_y(ui_weatherall, -44);
    lv_obj_set_align(ui_weatherall, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weatherall, "天气");
    lv_obj_set_style_text_font(ui_weatherall, &ui_font_Alibaba32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_today = lv_label_create(ui_weather);
    lv_obj_set_width(ui_today, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_today, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_today, -43);
    lv_obj_set_y(ui_today, 14);
    lv_obj_set_align(ui_today, LV_ALIGN_CENTER);
    lv_label_set_text(ui_today, "今日");
    lv_obj_set_style_text_color(ui_today, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_today, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_today, &ui_font_Alibaba16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tom = lv_label_create(ui_weather);
    lv_obj_set_width(ui_tom, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tom, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tom, -43);
    lv_obj_set_y(ui_tom, 43);
    lv_obj_set_align(ui_tom, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tom, "明日");
    lv_obj_set_style_text_color(ui_tom, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tom, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tom, &ui_font_Alibaba16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_todaysta = lv_label_create(ui_weather);
    lv_obj_set_width(ui_todaysta, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_todaysta, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_todaysta, -6);
    lv_obj_set_y(ui_todaysta, 14);
    lv_obj_set_align(ui_todaysta, LV_ALIGN_CENTER);
    lv_label_set_text(ui_todaysta, "晴");
    lv_obj_set_style_text_color(ui_todaysta, lv_color_hex(0xE4C327), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_todaysta, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_todaysta, &ui_font_Alibaba16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tomsta = lv_label_create(ui_weather);
    lv_obj_set_width(ui_tomsta, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tomsta, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tomsta, -6);
    lv_obj_set_y(ui_tomsta, 43);
    lv_obj_set_align(ui_tomsta, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tomsta, "雨");
    lv_obj_set_style_text_color(ui_tomsta, lv_color_hex(0x23C4B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tomsta, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tomsta, &ui_font_Alibaba16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_todaytem = lv_label_create(ui_weather);
    lv_obj_set_width(ui_todaytem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_todaytem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_todaytem, 37);
    lv_obj_set_y(ui_todaytem, 14);
    lv_obj_set_align(ui_todaytem, LV_ALIGN_CENTER);
    lv_label_set_text(ui_todaytem, "25°~30°");
    lv_obj_set_style_text_color(ui_todaytem, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_todaytem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tomtep = lv_label_create(ui_weather);
    lv_obj_set_width(ui_tomtep, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tomtep, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tomtep, 37);
    lv_obj_set_y(ui_tomtep, 44);
    lv_obj_set_align(ui_tomtep, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tomtep, "30°~35°");
    lv_obj_set_style_text_color(ui_tomtep, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tomtep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_weather);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -39);
    lv_obj_set_y(ui_Label5, -9);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xF29F0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_tem32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tepnow = lv_label_create(ui_weather);
    lv_obj_set_width(ui_tepnow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tepnow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tepnow, -12);
    lv_obj_set_y(ui_tepnow, -10);
    lv_obj_set_align(ui_tepnow, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tepnow, "27°");
    lv_obj_set_style_text_color(ui_tepnow, lv_color_hex(0x2D5DC2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tepnow, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_weather);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 13);
    lv_obj_set_y(ui_Label6, -9);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x0F94B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &ui_font_wet32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wetdata = lv_label_create(ui_weather);
    lv_obj_set_width(ui_wetdata, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wetdata, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wetdata, 42);
    lv_obj_set_y(ui_wetdata, -9);
    lv_obj_set_align(ui_wetdata, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wetdata, "60%");
    lv_obj_set_style_text_color(ui_wetdata, lv_color_hex(0x00F1E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wetdata, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}
